export const DAILY_QUOTES = [
  "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "In the middle of difficulty lies opportunity. - Albert Einstein",
  "It always seems impossible until it is done. - Nelson Mandela",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Do not wait for the perfect moment, take the moment and make it perfect.",
  "Small steps every day lead to big results over time.",
  "Believe you can and you are halfway there. - Theodore Roosevelt",
  "The best way to predict the future is to create it. - Peter Drucker",
  "Opportunities do not happen, you create them. - Chris Grosser",
  "Your limitation is only your imagination.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success does not just find you. You have to go out and get it.",
  "The harder you work for something, the greater you will feel when you achieve it.",
  "Do not stop when you are tired. Stop when you are done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It is going to be hard, but hard does not mean impossible.",
  "Do not wait for opportunity. Create it.",
  "Sometimes we are tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Push yourself, because no one else is going to do it for you.",
  "A person who never made a mistake never tried anything new. - Albert Einstein",
  "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
  "Act as if what you do makes a difference. It does. - William James",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "What you get by achieving your goals is not as important as what you become. - Zig Ziglar",
  "Whether you think you can or you think you cannot, you are right. - Henry Ford",
  "The way to get started is to quit talking and begin doing. - Walt Disney",
  "Do not be afraid to give up the good to go for the great. - John D. Rockefeller",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "The secret of getting ahead is getting started. - Mark Twain",
  "Quality is not an act, it is a habit. - Aristotle",
  "Perseverance is not a long race; it is many short races one after the other.",
  "Fall seven times, stand up eight.",
  "Every accomplishment starts with the decision to try.",
  "Motivation is what gets you started. Habit is what keeps you going. - Jim Ryun",
  "Energy and persistence conquer all things. - Benjamin Franklin",
  "Well done is better than well said. - Benjamin Franklin",
  "Nothing will work unless you do. - Maya Angelou",
  "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "Difficulties in life are intended to make us better, not bitter.",
  "You do not have to be great to start, but you have to start to be great. - Zig Ziglar",
  "Focus on being productive instead of busy.",
  "The expert in anything was once a beginner.",
  "A goal without a plan is just a wish.",
  "Progress, not perfection.",
  "Consistency is what transforms average into excellence.",
  "The comeback is always stronger than the setback.",
  "Discipline is choosing between what you want now and what you want most.",
  "Your only limit is you.",
  "Great things take time. Be patient with the process.",
  "Every day is a fresh start.",
  "You are capable of more than you know.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "Turn your wounds into wisdom. - Oprah Winfrey",
  "Be the energy you want to attract.",
  "One day or day one. You decide.",
  "Trust the timing of your life.",
  "The climb is what makes the summit sweet.",
  "You have got this. One step at a time.",
  "Do the work today that makes tomorrow easier.",
  "Stay patient and trust your journey.",
  "Good things come to those who hustle. - Anais Nin",
  "The grass is greener where you water it.",
  "Do small things with great love. - Mother Teresa",
  "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
  "You miss 100 percent of the shots you do not take. - Wayne Gretzky",
  "The way to get started is to quit talking and begin doing.",
  "If you can dream it, you can do it. - Walt Disney",
  "Do not let yesterday take up too much of today.",
  "It does not matter how slowly you go, as long as you do not stop. - Confucius",
  "Everything you have ever wanted is on the other side of fear.",
  "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Go confidently in the direction of your dreams. - Henry David Thoreau",
  "Winners are not people who never fail, but people who never quit.",
  "Aim for the moon. If you miss, you may hit a star. - W. Clement Stone",
  "Do not watch the clock; do what it does. Keep going. - Sam Levenson",
  "You are braver than you believe, stronger than you seem, and smarter than you think. - A.A. Milne",
  "Champions keep playing until they get it right. - Billie Jean King",
  "There is no elevator to success, you have to take the stairs.",
  "Work hard in silence, let success be your noise.",
  "Great work is done by people who are not afraid to be great. - Fernando Flores",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "You are exactly where you need to be to get where you are going.",
  "Every master was once a disaster.",
  "The only way out is through.",
  "What seems impossible today will one day become your warm up.",
  "Stay focused and never give up.",
  "Make each day your masterpiece. - John Wooden",
  "The best view comes after the hardest climb.",
  "Doubt kills more dreams than failure ever will.",
  "Big journeys begin with small steps.",
  "Growth is uncomfortable because you have never been here before.",
  "Chase the vision, not the money. The money will end up following you.",
  "Excellence is not a skill, it is an attitude. - Ralph Marston",
  "A river cuts through rock not because of its power but its persistence.",
  "Your future is created by what you do today, not tomorrow.",
];

export function getTodaysQuote(): string {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return DAILY_QUOTES[dayOfYear % DAILY_QUOTES.length];
}
